In [1]:
import torch
from torch_openreml.covariance.transform import TransformSigmoid

t = TransformSigmoid()
x = torch.tensor([-2.0, 0.0, 2.0])
t(x)

tensor([0.1192, 0.5000, 0.8808])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformSigmoid

t = TransformSigmoid()
x = torch.tensor([0.1, 0.5, 0.9])
t.inverse(x)

tensor([-2.1972,  0.0000,  2.1972])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformSigmoid

t = TransformSigmoid()
x = torch.tensor([0.0, 1.0])
t.grad(x)

tensor([0.2500, 0.1966])