In [1]:
import torch
from torch_openreml.covariance.transform import TransformIdentity

t = TransformIdentity()
x = torch.tensor([0.0, 1.0, -3.5])
t(x)

tensor([ 0.0000,  1.0000, -3.5000])

In [2]:
import torch
from torch_openreml.covariance.transform import TransformIdentity

t = TransformIdentity()
x = torch.tensor([2.0, -1.0])
t.inverse(x)

tensor([ 2., -1.])

In [3]:
import torch
from torch_openreml.covariance.transform import TransformIdentity

t = TransformIdentity()
x = torch.tensor([0.0])
t.grad(x)

tensor([1.])