In [1]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.trans_params(params)
mat.set_intermediates(params, {"sigma2": sigma2})
mat.get_intermediates(params)

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}

In [2]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.trans_params(params)
mat.set_intermediates(params, {"sigma2": sigma2})
mat.get_intermediates(params)

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}

In [3]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
sigma2 = mat.trans_params(params)
mat.set_intermediates(params, {"sigma2": sigma2})
print(mat.get_intermediates(params))
mat.reset_intermediates()
print(mat.get_intermediates(params))

{'sigma2': tensor([1.0000, 2.7183, 7.3891])}
None


In [4]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
mat.set_no_grad(index=0)
print(mat.no_grad_index)
print(mat.grad(torch.zeros(3)))

[0]
(tensor([[[0., 0., 0.],
         [0., 2., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 2.]]]), ['sigma^2_1', 'sigma^2_2'])


In [5]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
param_dict = {"sigma^2_0": torch.tensor([0.0]),
              "sigma^2_1": torch.tensor([0.5]),
              "sigma^2_2": torch.tensor([1.0])}
mat.from_param_dict(param_dict)

tensor([0.0000, 0.5000, 1.0000])

In [6]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
mat.to_param_dict(params)

{'sigma^2_0': tensor([0.]),
 'sigma^2_1': tensor([0.5000]),
 'sigma^2_2': tensor([1.])}

In [7]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
mat.trans_params(params)

tensor([1.0000, 2.7183, 7.3891])

In [8]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(3)
params = torch.tensor([0.0, 0.5, 1.0])
mat.trans_grad(params)

tensor([ 2.0000,  5.4366, 14.7781])

In [9]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.auto_grad(params)
grad, grad_names

(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])

In [10]:
import torch
from torch_openreml.covariance import DiagonalMatrix

mat = DiagonalMatrix(2)
params = torch.tensor([0.0, 0.5])
grad, grad_names = mat.grad(params)
grad, grad_names

(tensor([[[2.0000, 0.0000],
          [0.0000, 0.0000]],
 
         [[0.0000, 0.0000],
          [0.0000, 5.4366]]]),
 ['sigma^2_0', 'sigma^2_1'])